config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
    resources :comments
  end
  
  root "pins#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pin
  belongs_to :user
end

app/models/pin.rb
class Pin < ActiveRecord::Base
    acts_as_votable
    belongs_to :user
    has_many :comments
    
    has_attached_file :image, styles: { medium: "300x300>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
  has_many :comments
  
  has_attached_file :avatar, styles: { medium: "100x100>", :thumb => "50x50#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name << :avatar
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create
        @pin = Pin.find(params[:pin_id])
        @comment = Comment.create(params[:comment].permit(:content))
        @comment.user_id = current_user.id
        @comment.pin_id = @pin.id
        
        if @comment.save
            redirect_to pin_path(@pin)
        else
            render 'new'
        end
    end
    
    def destroy
        @pin = Pin.find(params[:pin_id])
        @comment = @pin.comments.find(params[:id])
        @comment.destroy
        redirect_to pin_path(@pin)
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @pins = Pin.all.order("created_at DESC")
    end
    
    def show
        @comments = Comment.where(pin_id: @pin)
    end
    
    def new
        @pin = current_user.pins.build
    end
    
    def create
        @pin = current_user.pins.build(pin_params)
        
        if @pin.save
            redirect_to @pin, notice: "Successfully created new Pin"
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @pin.update(pin_params)
            redirect_to @pin, notice: "Pin was successfully updated!"
        else
            render 'edit'
        end
    end
    
    def destroy
        @pin.destroy
        redirect_to root_path
    end
    
    def upvote
        @pin.upvote_by current_user
        redirect_to :back
    end
    
    private
    
    def pin_params
       params.require(:pin).permit(:title, :description, :image)
    end
    
    def find_pin
        @pin = Pin.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_comment.html.haml
.comment
    %p= comment.comment
    %p= comment.user.email
    - if comment.user == current_user
        = link_to "Delete", [comment.pin, comment], method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@pin, @pin.comments.build]) do |f|
    = f.input :content, label: "Reply to thread"
    = f.button :submit, class: "button"

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Travel Board
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Travel Board", root_path
      
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Travel", new_pin_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          .round-image-50
            = image_tag(current_user.avatar.url(:thumb))

      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
    - if @pin.errors.any?
        #errors
            %h2
            = pluralize(@pin.errors.count, "error")
            prevented this Pin from saving
            %ul
                - @pin.errors.full_messages.each do |msg|
                    %li= msg

    .form-group
        = f.input :image, input_html: { class: 'form-control' }
        
    .form-group
        = f.input :title, input_html: { class: 'form-control' }
        
    .form-group
        = f.input :description, input_html: { class: 'form-control' }
        
    = f.button :submit, class: "btn btn-primary"
        

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
    .row
        .panel.panel-default
            .panel-heading
                %h1 Edit Travel
            .panel-body
                %strong.center Current Image
                %br/
                = image_tag @pin.image.url(:medium)
                %br/
                = render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
    - @pins.each do |pin|
        .box.panel.panel-default
            = link_to (image_tag pin.image.url), pin
            .panel-body
                %h2= link_to pin.title, pin
                %p.user
                Author:
                = pin.user.name 
            .data.clearfix
                %p.buttons
                    %span
                        %i.fa.fa-comments-o.fa-2x
                        = pin.comments.count
                        Comments
                    

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
    .row
        .panel.panel-default
            .panel-heading
                %h1 New Form
            .panel-body
                = render 'form'

app/views/pins/show.html.haml
#pin_show.row
    .col-md-8.col-md-offset-2
        .panel.panel-default
            .panel-heading.pin_image
                = image_tag @pin.image.url
            .panel-body
                %h1= @pin.title
                Published at
                = @pin.created_at.strftime('%b, %d, %Y')
                %p.description= @pin.description
            .panel-footer
                .row
                    .col-md-6
                        .round-image-50
                            = image_tag @pin.user.avatar.url(:thumb)
                        %p.user
                        Author:
                        = @pin.user.name
                    .col-md-6
                        .btn-group.pull-right
                            = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                                %span.glyphicon.glyphicon-heart
                                    = @pin.get_upvotes.size
                            - if ( current_user == @pin.user ) and user_signed_in?
                                = link_to "Edit", edit_pin_path, class: "btn btn-default"
                                = link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
        .panel.panel-default
            .panel-body
                #comment
                    - @comments.each do |comment|
                        .btn-group.pull-right
                            - if comment.user == current_user
                                = link_to "Delete", [comment.pin, comment], method: :delete, data: { confirm: "Are you sure?" }
                        .round-image-50
                            = image_tag comment.user.avatar.url(:medium)
                        Submitted
                        = time_ago_in_words(comment.created_at)
                        ago by
                        %b= comment.user.name
                        %p.content= comment.content

                        %br/
            
                    = render 'comments/form'